services:
  backend: 
    build: ./backend

    #UNCOMMENT WHEN READY TO DEPLOY
    #environment:
    #  - DOCKER_ENV=true

    ports:
      - "8000:8000"
    
    env_file:
      - .env
    
  frontend:
    build: ./frontend
    ports:
      - "80:80"

    depends_on:
      - backend